sudo: required
language: node_js

services:
  - docker

node_js:
  - "10"
  - "12"
  - node
env:
  - MONGOOSE_VERSION=5.6
  - MONGOOSE_VERSION=5.7
  - MONGOOSE_VERSION=

install:
  - yarn
  - if [[ ! -z "$MONGOOSE_VERSION" ]]; then yarn add -D "mongoose@~$MONGOOSE_VERSION"; fi;

before_script:
  - docker-compose up -d

script:
  - yarn lint
  - yarn test
