sudo: required
language: node_js

services:
  - docker

node_js:
  - "10"
  - "11"
  - "12"
env:
  - MONGOOSE_VERSION=5.6
  - MONGOOSE_VERSION=5.7
  - MONGOOSE_VERSION=

install:
  - yarn
  - [[ ! -z "$MONGOOSE_VERSION" ]] && yarn add -D "mongoose@~$MONGOOSE_VERSION"

before_script:
  - docker-compose up -d

script:
  - yarn lint
  - yarn test
